<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Login extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        
    }

    function index()
    {	
    if ($this->session->userdata("email")) {
        redirect('dashboard');
    } else {
        $this->load->view('login/index');
    }
    }
    function auth(){
        $this->load->library('form_validation');

		$this->form_validation->set_rules('password', 'password', 'required');
		$this->form_validation->set_rules('email', 'email', 'required');

		$params = array(
			'password' => md5($this->input->post('password')),
			'email' => $this->input->post('email'),
			'is_active'=>1
		);
		if ($this->form_validation->run()) {
			$this->load->model('Account_model');
			// $data = $this->Account_model->login($params);
			// $logo=$this->Account_model->get_logo();
			if ($params) {
				if ($params['is_active'] == 1) {
					$params['full_name']="Aqib Ali";
					$this->session->set_userdata($params);
					//$this->session->set_userdata($logo);
					// $_SESSION['logo'] = $logo;
					redirect('Dashboard');
				} else {
					$this->session->set_flashdata('error', 'Your account is deactivated. Please contact administrator');
					redirect('login', 'refresh');
				}
			} else {
				$this->session->set_flashdata('error', 'Email / Password combinaion does not exist.');
				redirect('login', 'refresh');
			}
		} else {
			$this->session->set_flashdata('error', 'Fields can not be empty.');
			redirect('login', 'refresh');
		}
    }
    public function logout(){
        $this->session->sess_destroy();
		redirect('login');
    }

}
