<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Account_model extends CI_Model
{
	function __construct()
	{
		parent::__construct();
	}

	function signup($arr){
	    $if_exist = $this->db->query("SELECT * FROM users WHERE email ='{$arr['email']}' and is_active=1 order by id DESC")->row_array();
        if(!isset($if_exist)){
            $this->db->insert('users', $arr);
        }
    }

	function get_user_byId($id)
	{
		return $this->db->get_where('users', array('id' => $id))->row_array();
	}


	function update_tenancy($uid, $tid, $user, $tenency){
		// $e=str_replace("%40","@",$user['email']);
        // $if_exist = $this->db->query("SELECT * FROM users WHERE email ='{$e}'")->row_array();
        // if($if_exist['email']== $e){
		// 	return false;
        // }
        // else{
			$this->db->trans_start();
			$this->db->where('id', $uid);
			$this->db->update('users', $user);
			$this->db->where('tid', $tid);
			$this->db->update('tenancy', $tenency);
			$this->db->trans_complete();
			return true;
		// }
	}

	function login($params)
	{
		$this->db->order_by('id', 'desc');
		return $this->db->get_where('users', $params)->row_array();
	}
	function get_logo(){
		$this->db->order_by('id', 'desc');
		return $this->db->get('logo')->row_array();
	}



}
